#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop acornd.service >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
